version: '3.9'

services:
  jira:
    container_name: jira
    depends_on:
      - postgresql
    image: atlassian/jira-software:latest
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '8001:8080'
    environment:
      ATL_JDBC_URL: jdbc:postgresql://postgresql:5432/jira_db
      ATL_JDBC_USER: jira_usr
      ATL_JDBC_PASSWORD=: jira_pwd

  postgresql:
    container_name: postgres
    image: postgres:latest
    expose:
      - '5432'
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jira_usr
      POSTGRES_PASSWORD: jira_pwd
      POSTGRES_DB: jira_db
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jira_usr -d jira_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge