---
driver:
  name: podman
platforms:
  - name: ubuntu
    image: docker.io/ubuntu:latest
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy
