galaxy_info:
  author: Aleksey Kashin
  description: The role installs and configures the Vector on selected hosts
  company: no company
  license: MIT
  min_ansible_version: 2.17.0
  galaxy_tags:
    - vector
dependencies: []
