---

- name: Install Clickhouse
  hosts: clickhouse
  become: true
  vars:
    clickhouse_dbs_custom:
      - { name: vector, state: present }
    clickhouse_dbs_table_custom:
      - { db: vector, table: server_log }
  roles:
    - clickhouse
  post_tasks:
    - name: Create table on schema for Vector service
      ansible.builtin.command: "clickhouse-client -q 'CREATE TABLE {{ item.db }}.{{ item.table }}(message String) ENGINE = TinyLog();'"
      with_items: "{{ clickhouse_dbs_table_custom }}"
      register: create_table
      failed_when: create_table.rc != 0 and create_table.rc != 57
      changed_when: create_table.rc == 0

- name: Install Vector
  hosts: clickhouse
  become: true
  vars:
    vector_config:
      sources:
        demo_logs:
          type: demo_logs
          format: syslog
        in:
          type: stdin
      sinks:
        to_clickhouse:
          type: clickhouse
          inputs:
            - demo_logs
          database: vector
          endpoint: http://localhost:8123
          table: server_log
          compression: gzip
          healthcheck: true
          skip_unknown_fields: true
  roles:
    - vector

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  roles:
    - lighthouse
