---
- name: Docker pull images
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Docker pull ubuntu OS
      community.docker.docker_image:
        name: ubuntu
        tag: latest
        source: pull

- name: Docker container ubuntu up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create docker container for clickhouse-01
      community.docker.docker_container:
        name: clickhouse-01
        image: ubuntu:latest
        state: started
        restart_policy: always
        interactive: true
        tty: true
        detach: true

- name: Isntall python on Debian hosts
  hosts: clickhouse
  gather_facts: false
  tasks:
    # - name: Check if python install
    #   ansible.builtin.command: python3 --version
    #   register: python_valid
    #   ignore_errors: true
    #   changed_when: false
    - name: Update pack manager and install python
      ansible.builtin.raw: "{{ item }}"
      loop:
        - apt-get update
        - apt-get -y install python3
      register: my_output
      changed_when: my_output.rc != 0
      # when: python_valid.failed

- name: Isntall [pkg | clickhouse | vector] on Debian hosts
  hosts: clickhouse
  roles:
    - debian
    - clickhouse
    - vector

- name: Create Clickhouse DB
  hosts: clickhouse
  tasks:
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
