vector_repo_url: "https://apt.vector.dev"
vector_repo_pkg: "deb"
vector_repo_ver: "stable"
vector_gpg: "https://keys.datadoghq.com/DATADOG_APT_KEY_CURRENT.public"
vector_packages:
  - vector
vector_config_path: "/etc/vector/"
vector_config:
  data_dir: "/var/lib/vector"
  sources:
    clickhouse_server_logs:
      type: "file"
      include:
        - "/var/log/clickhouse-server/clickhouse-server.log"
  sinks:
    print:
      type: "console"
      inputs:
        - "clickhouse_server_logs"
      encoding:
        codec: "text"
