input {
  beats {
    port => 5046
  }
}

filter{
  json{
      source => "message"
   }
  date {
    match => ["asctime", "yyyy-MM-dd HH:mm:ss,SSS"]
    timezone => "UTC"
    target => "@timestamp"
    remove_field => ["asctime"]
  }
}

output {
  elasticsearch { 
    hosts => ["es-hot:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
  stdout { 
    codec => rubydebug 
  }
}
