---
- name: Restart Nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
# - name: Restart Nginx
#   become: true
#   ansible.builtin.systemd:
#     name: nginx
#     state: restarted
#     daemon_reload: true
