---
local:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: docker
