---
all:
  hosts:
    nexus-01:
      ansible_host: 89.169.147.17
    teamcity-01:
      ansible_host: 89.169.147.17
  children:
    nexus:
      hosts:
        nexus-01:
    teamcity:
      hosts:
        nexus-01:
  # vars:
  #   ansible_connection_type: paramiko
  #   ansible_user: <user>