#cloud-config
users:
  - name: alekseykashin
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_public_key}
package_update: true
package_upgrade: false
packages:
  - sudo
  - wget
  - tar
  - unzip
  - curl
  - systemd