node("centos"){
    stage("Git checkout"){
        sh 'rm -rf ./example-playbook'
        sh 'git clone https://github.com/aragastmatb/example-playbook.git && cd example-playbook'
    }
    stage("Sample define secret_check"){
        secret_check=true
    }
    stage("Run playbook"){
        if (secret_check){
            sh 'cd example-playbook/ && ansible-playbook site.yml -i inventory/prod.yml'
        }
        else{
            sh 'cd example-playbook/ && ansible-playbook site.yml -i inventory/prod.yml --check --diff'
        }
        
    }
}
